name: Validate Templates
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-yaml:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_on_error: "true"
